name: poqo
description: "The pocket companion for a calmer, better you. One small step daily."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
